version: '3.8'

services:
  comprehend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comprehend-api
    ports:
      - "3000:3000"
    volumes:
      - ../api:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - comprehend-mongo
    tty: true
    command: >
      sh -c "npm install && npm run build && ls && npm run start:dev"

  risk-engine:
    build:
      context: ../risk-engine
      dockerfile: Dockerfile
    container_name: risk-engine
    ports:
      - "8000:8000"
    # se você quiser hot reload em dev, dá pra mapear volume e usar --reload (opcional)
    volumes:
     - ../risk-engine:/app
    environment:
      PYTHONUNBUFFERED: "1"
    tty: true

  comprehend-mongo:
    image: mongo:latest
    container_name: comprehend-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db

# Definição do Volume para persistir os dados do MongoDB
volumes:
  mongodb_data:
